#Importando bibliotecas e dados

In [ ]:
import pandas as pd

In [ ]:
dados = pd.read_csv('aluguel.csv', sep = ';')


#análise dos dados

In [ ]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32960 entries, 0 to 32959
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Tipo        32960 non-null  object
 1   Bairro      32960 non-null  object
 2   Quartos     32960 non-null  int64
 3   Vagas       32960 non-null  int64
 4   Suites      32960 non-null  int64
 5   Area        32960 non-null  int64
 6   Valor       32943 non-null  float64
 7   Condominio  28867 non-null  float64
 8   IPTU        22723 non-null  float64
dtypes: float64(3), int64(4), object(2)
memory usage: 2.3+ MB

In [ ]:
dados.head()

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
0,Quitinete,Copacabana,1,0,0,40,1700.0,500.0,60.0
1,Casa,Jardim Botânico,2,0,1,100,7000.0,NaN,NaN
2,Conjunto Comercial/Sala,Barra da Tijuca,0,4,0,150,5200.0,4020.0,1111.0
3,Apartamento,Centro,1,0,0,15,800.0,390.0,20.0
4,Apartamento,Higienópolis,1,0,0,48,800.0,230.0,NaN

In [ ]:
dados.dtypes

Tipo           object
Bairro         object
Quartos         int64
Vagas           int64
Suites          int64
Area            int64
Valor         float64
Condominio    float64
IPTU          float64
dtype: object

In [ ]:
tipos_de_dados = pd.DataFrame(dados.dtypes, columns = ['Tipos de Dados'])

In [ ]:
tipos_de_dados

           Tipos de Dados
Tipo               object
Bairro             object
Quartos             int64
Vagas               int64
Suites              int64
Area                int64
Valor             float64
Condominio        float64
IPTU              float64

In [ ]:
dados.shape

(32960, 9)

In [ ]:
print('A base de dados apresenta {} registros (imóveis) e {} variáveis/características'.format(dados.shape[0], dados.shape[1]))

A base de dados apresenta 32960 registros (imóveis) e 9 variáveis/características

In [ ]:
dados.head()

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
0,Quitinete,Copacabana,1,0,0,40,1700.0,500.0,60.0
1,Casa,Jardim Botânico,2,0,1,100,7000.0,NaN,NaN
2,Conjunto Comercial/Sala,Barra da Tijuca,0,4,0,150,5200.0,4020.0,1111.0
3,Apartamento,Centro,1,0,0,15,800.0,390.0,20.0
4,Apartamento,Higienópolis,1,0,0,48,800.0,230.0,NaN

#Tipos de imóveis

In [ ]:
tipo_de_imovel = dados['Tipo']

In [ ]:
tipo_de_imovel.drop_duplicates()

0                          Quitinete
1                               Casa
2            Conjunto Comercial/Sala
3                        Apartamento
7                 Casa de Condomínio
16                    Prédio Inteiro
17                              Flat
29                        Loja/Salão
80           Galpão/Depósito/Armazém
83                    Casa Comercial
117                     Casa de Vila
159                   Terreno Padrão
207                      Box/Garagem
347                             Loft
589      Loja Shopping/ Ct Comercial
2157                         Chácara
3354           Loteamento/Condomínio
4379                           Sítio
4721                   Pousada/Chalé
6983                          Studio
9687                           Hotel
23614                      Indústria
Name: Tipo, dtype: object

In [ ]:
tipo_de_imovel.index = range(tipo_de_imovel.shape[0])

In [ ]:
tipo_de_imovel.index

RangeIndex(start=0, stop=32960, step=1)

In [ ]:
tipo_de_imovel.head()

0                  Quitinete
1                       Casa
2    Conjunto Comercial/Sala
3                Apartamento
4                Apartamento
Name: Tipo, dtype: object

In [ ]:
list(dados['Tipo'].drop_duplicates())

['Quitinete',
 'Casa',
 'Conjunto Comercial/Sala',
 'Apartamento',
 'Casa de Condomínio',
 'Prédio Inteiro',
 'Flat',
 'Loja/Salão',
 'Galpão/Depósito/Armazém',
 'Casa Comercial',
 'Casa de Vila',
 'Terreno Padrão',
 'Box/Garagem',
 'Loft',
 'Loja Shopping/ Ct Comercial',
 'Chácara',
 'Loteamento/Condomínio',
 'Sítio',
 'Pousada/Chalé',
 'Studio',
 'Hotel',
 'Indústria']

#Visualização apenas de residências do tipo casa

In [ ]:
residencial = ['Quitinete',
 'Casa',
 'Apartamento',
 'Casa de Condomínio',
 'Casa de Vila',
]

In [ ]:
selecao = dados['Tipo'].isin(residencial)
selecao

0         True
1         True
2        False
3         True
4         True
         ...
32955     True
32956     True
32957     True
32958     True
32959    False
Name: Tipo, Length: 32960, dtype: bool

In [ ]:
dados_residencial = dados[selecao]

In [ ]:
list(dados_residencial['Tipo'].drop_duplicates())

['Quitinete', 'Casa', 'Apartamento', 'Casa de Condomínio', 'Casa de Vila']

In [ ]:
dados_residencial.index = range(dados_residencial.shape[0])

In [ ]:
dados_residencial

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
0,Quitinete,Copacabana,1,0,0,40,1700.0,500.0,60.0
1,Casa,Jardim Botânico,2,0,1,100,7000.0,NaN,NaN
2,Apartamento,Centro,1,0,0,15,800.0,390.0,20.0
3,Apartamento,Higienópolis,1,0,0,48,800.0,230.0,NaN
4,Apartamento,Vista Alegre,3,1,0,70,1200.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...
22575,Apartamento,Méier,2,0,0,70,900.0,490.0,48.0
22576,Quitinete,Centro,0,0,0,27,800.0,350.0,25.0
22577,Apartamento,Jacarepaguá,3,1,2,78,1800.0,800.0,40.0
22578,Apartamento,São Francisco Xavier,2,1,0,48,1400.0,509.0,37.0
22579,Apartamento,Leblon,2,0,0,70,3000.0,760.0,NaN

In [ ]:
dados_residencial.to_csv("aluguel_residencial.csv", sep = ";", index = False)

In [ ]:
dados_residencial2 = pd.read_csv("aluguel_residencial.csv", sep = ";")

Selecione somente os imóveis classificados com tipo 'Apartamento'.

In [ ]:
selecao = dados['Tipo'] == 'Apartamento'
n1 = dados[selecao].shape[0]
n1

19532

Selecione os imóveis classificados com tipos 'Casa', 'Casa de Condomínio' e 'Casa de Vila'.

In [ ]:
selecaoA = dados['Tipo'] == 'Casa'
selecaoB = dados['Tipo'] == 'Casa de Condomínio'
selecaoC = dados['Tipo'] == 'Casa de Vila'
casas: selecaoA + selecaoB + selecaoC
casa = casas[casas].shape[0]
print("o número de moradias do tipo casa é de :", casa)

o número de moradias do tipo casa é de  2212

Selecione os imóveis com área entre 60 e 100 metros quadrados, incluindo os limites.

In [ ]:
imoveis = dados_residencial['Area']
imoveis

0         40
1        100
2         15
3         48
4         70
        ...
22575     70
22576     27
22577     78
22578     48
22579     70
Name: Area, Length: 22580, dtype: int64

In [ ]:
selecao = (dados['Area'] >= 60) & (dados['Area'] <= 100)
n3= dados[selecao].shape[0]
n3

10187

Selecione os imóveis que tenham pelo menos 4 quartos e aluguel menor que R$ 2.000,00.

In [ ]:
selecao = (dados["Quartos"] >= 4) & (dados['Valor'] < 2000)
n4 = dados[selecao].shape[0]
n4

43

#Tratamento de dados faltantes

In [ ]:
dados.isnull()

        Tipo  Bairro  Quartos  Vagas  Suites   Area  Valor  Condominio   IPTU
0      False   False    False  False   False  False  False       False  False
1      False   False    False  False   False  False  False        True   True
2      False   False    False  False   False  False  False       False  False
3      False   False    False  False   False  False  False       False  False
4      False   False    False  False   False  False  False       False   True
...      ...     ...      ...    ...     ...    ...    ...         ...    ...
32955  False   False    False  False   False  False  False       False  False
32956  False   False    False  False   False  False  False       False  False
32957  False   False    False  False   False  False  False       False  False
32958  False   False    False  False   False  False  False       False   True
32959  False   False    False  False   False  False  False       False  False

[32960 rows x 9 columns]

In [ ]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32960 entries, 0 to 32959
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Tipo        32960 non-null  object
 1   Bairro      32960 non-null  object
 2   Quartos     32960 non-null  int64
 3   Vagas       32960 non-null  int64
 4   Suites      32960 non-null  int64
 5   Area        32960 non-null  int64
 6   Valor       32943 non-null  float64
 7   Condominio  28867 non-null  float64
 8   IPTU        22723 non-null  float64
dtypes: float64(3), int64(4), object(2)
memory usage: 2.3+ MB

In [ ]:
dados[dados["Valor"].isnull()]

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
76,Apartamento,Barra da Tijuca,2,1,1,70,NaN,970.0,68.0
2186,Apartamento,Leme,2,0,0,75,NaN,878.0,NaN
2456,Casa,Campo Grande,3,4,3,363,NaN,NaN,NaN
2646,Loja/Salão,Barra da Tijuca,0,2,0,80,NaN,NaN,NaN
2941,Apartamento,Botafogo,2,0,0,95,NaN,1010.0,170.0
2973,Apartamento,Copacabana,2,0,0,72,NaN,850.0,NaN
6598,Loja/Salão,Andaraí,0,0,0,326,NaN,NaN,1140.0
7302,Casa,Campo Grande,3,2,1,100,NaN,NaN,NaN
12683,Apartamento,Leme,2,0,1,75,NaN,878.0,NaN
13229,Apartamento,Glória,3,0,1,135,NaN,910.0,228.0
13525,Apartamento,Gávea,3,1,1,105,NaN,880.0,221.0
13579,Conjunto Comercial/Sala,Botafogo,0,3,0,200,NaN,10.0,NaN
20948,Conjunto Comercial/Sala,Freguesia (Jacarepaguá),0,1,0,24,NaN,500.0,74.0
21822,Loja Shopping/ Ct Comercial,Barra da Tijuca,0,2,0,77,NaN,3600.0,1390.0
23056,Conjunto Comercial/Sala,Botafogo,0,0,0,900,NaN,10.0,NaN
24805,Conjunto Comercial/Sala,Botafogo,0,0,0,500,NaN,10.0,NaN
29166,Conjunto Comercial/Sala,Botafogo,0,1,0,50,NaN,10.0,NaN

In [ ]:
A = dados.shape[0]
dados.dropna(subset = ["Valor"], inplace=True)
B = dados.shape[0]
A-B

17

In [ ]:
dados[dados['Condominio'].isnull()].shape[0]

4089

In [ ]:
selecao = (dados['Tipo'] == 'Apartamento') & (dados['Condominio'].isnull())

In [ ]:
A = dados.shape[0]
dados = dados[~selecao]
B = dados.shape[0]
A-B

745

In [ ]:
dados.fillna(0)

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
0,Quitinete,Copacabana,1,0,0,40,1700.0,500.0,60.0
1,Casa,Jardim Botânico,2,0,1,100,7000.0,0.0,0.0
2,Conjunto Comercial/Sala,Barra da Tijuca,0,4,0,150,5200.0,4020.0,1111.0
3,Apartamento,Centro,1,0,0,15,800.0,390.0,20.0
4,Apartamento,Higienópolis,1,0,0,48,800.0,230.0,0.0
...,...,...,...,...,...,...,...,...,...
32955,Quitinete,Centro,0,0,0,27,800.0,350.0,25.0
32956,Apartamento,Jacarepaguá,3,1,2,78,1800.0,800.0,40.0
32957,Apartamento,São Francisco Xavier,2,1,0,48,1400.0,509.0,37.0
32958,Apartamento,Leblon,2,0,0,70,3000.0,760.0,0.0
32959,Conjunto Comercial/Sala,Centro,0,0,0,250,6500.0,4206.0,1109.0

In [ ]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 32198 entries, 0 to 32959
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Tipo        32198 non-null  object
 1   Bairro      32198 non-null  object
 2   Quartos     32198 non-null  int64
 3   Vagas       32198 non-null  int64
 4   Suites      32198 non-null  int64
 5   Area        32198 non-null  int64
 6   Valor       32198 non-null  float64
 7   Condominio  28854 non-null  float64
 8   IPTU        22610 non-null  float64
dtypes: float64(3), int64(4), object(2)
memory usage: 2.5+ MB

In [ ]:
dados.to_csv("aluguel_residencial_final.csv", sep ='')

#Inserção de novos valores

In [165]:
dados['Valor Bruto'] = dados['Valor'] + dados['Condominio'] + dados['IPTU']

<ipython-input-165-07ac9c5692c0>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados['Valor Bruto'] = dados['Valor'] + dados['Condominio'] + dados['IPTU']

In [166]:
dados['Valor m2'] = dados['Valor']/dados['Area']

<ipython-input-166-1ee3d8e028e3>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados['Valor m2'] = dados['Valor']/dados['Area']

In [167]:
dados['Valor m2'] = dados['Valor m2'].round(2)

<ipython-input-167-b771744966fd>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados['Valor m2'] = dados['Valor m2'].round(2)

In [168]:
dados['Valor Bruto m2'] = (dados['Valor Bruto']/dados['Area']).round(2)

<ipython-input-168-41bb81217273>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados['Valor Bruto m2'] = (dados['Valor Bruto']/dados['Area']).round(2)

In [169]:
casa = ['Casa', 'Casa de Condomínio', 'Casa de Vila']

In [170]:
dados['Tipo Agregado'] = dados['Tipo'].apply(lambda x: 'Casa' if x in casa else 'Apartamento')

<ipython-input-170-5b673d156776>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados['Tipo Agregado'] = dados['Tipo'].apply(lambda x: 'Casa' if x in casa else 'Apartamento')

In [171]:
dados

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU,Valor Bruto,Valor m2,Valor Bruto m2,Tipo Agregado
0,Quitinete,Copacabana,1,0,0,40,1700.0,500.0,60.0,2260.0,42.50,56.50,Apartamento
1,Casa,Jardim Botânico,2,0,1,100,7000.0,NaN,NaN,NaN,70.00,NaN,Casa
2,Conjunto Comercial/Sala,Barra da Tijuca,0,4,0,150,5200.0,4020.0,1111.0,10331.0,34.67,68.87,Apartamento
3,Apartamento,Centro,1,0,0,15,800.0,390.0,20.0,1210.0,53.33,80.67,Apartamento
4,Apartamento,Higienópolis,1,0,0,48,800.0,230.0,NaN,NaN,16.67,NaN,Apartamento
...,...,...,...,...,...,...,...,...,...,...,...,...,...
32955,Quitinete,Centro,0,0,0,27,800.0,350.0,25.0,1175.0,29.63,43.52,Apartamento
32956,Apartamento,Jacarepaguá,3,1,2,78,1800.0,800.0,40.0,2640.0,23.08,33.85,Apartamento
32957,Apartamento,São Francisco Xavier,2,1,0,48,1400.0,509.0,37.0,1946.0,29.17,40.54,Apartamento
32958,Apartamento,Leblon,2,0,0,70,3000.0,760.0,NaN,NaN,42.86,NaN,Apartamento
32959,Conjunto Comercial/Sala,Centro,0,0,0,250,6500.0,4206.0,1109.0,11815.0,26.00,47.26,Apartamento

#Excluindo variáveis

In [174]:
dados.drop(['Valor Bruto', "Valor Bruto m2"], axis = 1, inplace = True)

<ipython-input-174-77a95f031ec5>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados.drop(['Valor Bruto', "Valor Bruto m2"], axis = 1, inplace = True)

In [175]:
dados.head()

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU,Valor m2,Tipo Agregado
0,Quitinete,Copacabana,1,0,0,40,1700.0,500.0,60.0,42.50,Apartamento
1,Casa,Jardim Botânico,2,0,1,100,7000.0,NaN,NaN,70.00,Casa
2,Conjunto Comercial/Sala,Barra da Tijuca,0,4,0,150,5200.0,4020.0,1111.0,34.67,Apartamento
3,Apartamento,Centro,1,0,0,15,800.0,390.0,20.0,53.33,Apartamento
4,Apartamento,Higienópolis,1,0,0,48,800.0,230.0,NaN,16.67,Apartamento

#Estatísticas descritivas

In [176]:
bairros = ['Barra da Tijuca', 'Copacabana', 'Ipanema', 'Leblon', 'Botafogo', 'Flamengo', 'Tijuca']
selecao = dados['Bairro'].isin(bairros)
dados = dados[selecao]

In [177]:
dados['Bairro'].drop_duplicates()

0           Copacabana
2      Barra da Tijuca
16            Botafogo
21              Tijuca
25              Leblon
27             Ipanema
110           Flamengo
Name: Bairro, dtype: object

In [178]:
grupo_bairro = dados.groupby('Bairro')

In [179]:
for bairro, dados in grupo_bairro:
    print(bairro)

Barra da Tijuca
Botafogo
Copacabana
Flamengo
Ipanema
Leblon
Tijuca

In [180]:

for bairro, dados in grupo_bairro:
    print('{} -> {}'.format(bairro, dados.Valor.mean()))

Barra da Tijuca -> 9035.204743465634
Botafogo -> 19709.716814159292
Copacabana -> 4514.538436482085
Flamengo -> 6923.498132004981
Ipanema -> 10455.031861629495
Leblon -> 11072.38930774503
Tijuca -> 2964.5705794947994

In [181]:
grupo_bairro['Valor'].mean()

Bairro
Barra da Tijuca     9035.204743
Botafogo           19709.716814
Copacabana          4514.538436
Flamengo            6923.498132
Ipanema            10455.031862
Leblon             11072.389308
Tijuca              2964.570579
Name: Valor, dtype: float64

In [182]:
grupo_bairro[['Valor', 'Condominio']].mean().round(2)

                    Valor  Condominio
Bairro
Barra da Tijuca   9035.20     3599.61
Botafogo         19709.72     3309.87
Copacabana        4514.54     1212.06
Flamengo          6923.50     1921.29
Ipanema          10455.03     2360.60
Leblon           11072.39     2290.44
Tijuca            2964.57      854.95

In [183]:
grupo_bairro['Valor'].describe().round(2)

,count,mean,std,min,25%,50%,75%,max
Bairro,,,,,,,,
Barra da Tijuca,6198.0,9035.20,30328.23,100.0,2000.0,3500.0,8000.0,738197.0
Botafogo,1356.0,19709.72,129879.42,299.0,2500.0,4000.0,11000.0,4500000.0
Copacabana,3070.0,4514.54,6502.57,100.0,1900.0,3000.0,4900.0,198000.0
Flamengo,803.0,6923.50,15848.59,200.0,1900.0,3000.0,5300.0,212544.0
Ipanema,2197.0,10455.03,21002.14,100.0,4000.0,6900.0,12000.0,800000.0
Leblon,1459.0,11072.39,20830.80,100.0,4500.0,7000.0,11900.0,430000.0
Tijuca,1346.0,2964.57,8017.45,320.0,1400.0,1800.0,2500.0,230000.0

In [231]:
bairros = ['Barra da Tijuca', 'Copacabana', 'Ipanema', 'Leblon', 'Botafogo', 'Flamengo', 'Tijuca']
bairros

['Barra da Tijuca',
 'Copacabana',
 'Ipanema',
 'Leblon',
 'Botafogo',
 'Flamengo',
 'Tijuca']

In [237]:
selecao = dados['Bairro'].isin(bairros)
selecao

21       True
24       True
28       True
114      True
118      True
         ...
32742    True
32800    True
32819    True
32878    True
32950    True
Name: Bairro, Length: 1346, dtype: bool

In [238]:
dados = dados[selecao]
dados

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU,Valor m2,Tipo Agregado
21,Apartamento,Tijuca,2,1,0,110,1900.0,700.0,138.0,17.27,Apartamento
24,Apartamento,Tijuca,2,1,0,78,2000.0,700.0,NaN,25.64,Apartamento
28,Apartamento,Tijuca,1,0,0,48,750.0,772.0,25.0,15.62,Apartamento
114,Apartamento,Tijuca,2,1,0,80,1800.0,1100.0,84.0,22.50,Apartamento
118,Apartamento,Tijuca,3,1,0,172,2700.0,780.0,170.0,15.70,Apartamento
...,...,...,...,...,...,...,...,...,...,...,...
32742,Apartamento,Tijuca,2,1,0,78,1800.0,620.0,62.0,23.08,Apartamento
32800,Apartamento,Tijuca,2,0,0,69,1700.0,760.0,62.0,24.64,Apartamento
32819,Apartamento,Tijuca,2,3,0,70,1680.0,230.0,45.0,24.00,Apartamento
32878,Apartamento,Tijuca,3,1,0,75,1900.0,860.0,141.0,25.33,Apartamento
32950,Apartamento,Tijuca,1,0,0,28,1000.0,360.0,25.0,35.71,Apartamento

In [239]:
dados['Bairro'].drop_duplicates()

21    Tijuca
Name: Bairro, dtype: object

In [234]:
grupo_bairro = dados.groupby('Bairro')

In [229]:
for bairro, dados in grupo_bairro:
    print(bairro)

Tijuca